name: Publish Python Package
on: 
  release: 
    types: [created,edited]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - run: pip install setuptools wheel twine

      - name: Build and publish
        env: 
          TWINE_USERNAME: ${{ secrets.TWINE_PASSWORD }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: python setup.py sdist bdist_wheel
      - run: twine upload --verbose --repository-url https://test.pypi.org/legacy/ -u ${{ secrets.TWINE_USERNAME }} -p ${{ secrets.TWINE_PASSWORD }} dist/*


